sudo: required

services:
  - docker

before_install:
  - docker build -t steviebiddles/docker-react-frontend -f Dockerfile.dev .

script:
  - docker run steviebiddles/docker-react-frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "Docker React Frontend"
  env: "DockerReactFrontend-env"
  bucket_name: "elasticbeanstalk-eu-west-1-242772714209"
  bucket_path: "Docker React Frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY