sudo: required

services:
  - docker

before_install:
  - docker build -t steviebiddles/docker-react-frontend -f Dockerfile.dev .

script:
  - docker run steviebiddles/docker-react-frontend npm run test -- --coverage